void cypress_init(void);
void cypress_irq();
void cypress_start_bind_send(bool use_dsm2);
void cypress_start_send(bool use_dsm2);
void cypress_start_FCC_test(void);
void cypress_start_factory_test(uint8_t test_mode);
void cypress_next_FCC_power(void);
void cypress_set_CW_mode(bool cw);
void cypress_change_FCC_channel(int8_t change);
uint8_t get_tx_power(void);
int8_t get_FCC_chan(void);
uint8_t get_FCC_power(void);
void cypress_set_pps_rssi(void);
uint8_t get_telem_rssi(void);
uint8_t get_send_pps(void);
uint8_t get_telem_pps(void);
